import {
  FaJava,
  FaPython,
  FaDocker,
  FaGitAlt,
  FaLinux,
  FaReact,
  FaNodeJs,
  FaExternalLinkAlt,
  FaServer,
  FaHtml5,
  FaCss3,
  FaAws,
  FaNpm,
} from "react-icons/fa";
import { FaCircleDot } from "react-icons/fa6";
import { FcScatterPlot } from "react-icons/fc";
import { GrServices } from "react-icons/gr";
import { PiFlowArrow } from "react-icons/pi";
import {
  SiTypescript,
  SiRust,
  SiFastapi,
  SiPostgresql,
  SiMongodb,
  SiNextdotjs,
  SiTailwindcss,
  SiGithubactions,
  SiJavascript,
  SiGnubash,
  SiExpress,
  SiRedux,
  SiMui,
  SiRecoil,
  SiPandas,
  SiNumpy,
  SiScikitlearn,
  SiStreamlit,
  SiGooglecloud,
  SiLangchain,
} from "react-icons/si";
import { TbHexagonLetterC, TbPrompt, TbSql } from "react-icons/tb";

export const SKILL_ICONS: Record<string, React.ElementType> = {
  Java: FaJava,
  Python: FaPython,
  TypeScript: SiTypescript,
  SQL: TbSql,
  Bash: SiGnubash,
  Rust: SiRust,
  "RESTful APIs": FaServer,
  FastAPI: SiFastapi,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  "Node.js": FaNodeJs,
  Microservices: GrServices,
  Docker: FaDocker,
  "Docker Compose": FaDocker,
  "GitHub Actions": SiGithubactions,
  Git: FaGitAlt,
  "Linux (Shell Scripting)": FaLinux,
  "Next.js": SiNextdotjs,
  React: FaReact,
  "Tailwind CSS": SiTailwindcss,
  JavaScript: SiJavascript,
  C: TbHexagonLetterC,
  "Express.js": SiExpress,
  Redux: SiRedux,
  Zustand: FaCircleDot,
  HTML: FaHtml5,
  CSS: FaCss3,
  MUI: SiMui,
  Recoil: SiRecoil,
  Pandas: SiPandas,
  NumPy: SiNumpy,
  "Scikit-learn": SiScikitlearn,
  Streamlit: SiStreamlit,
  Matplotlib: FcScatterPlot,
  Seaborn: FcScatterPlot,
  GCP: SiGooglecloud,
  AWS: FaAws,
  "React Flow": PiFlowArrow,
  LangChain: SiLangchain,
  LangGraph: SiLangchain,
  "Prompt Engineering": TbPrompt,
  NPM: FaNpm,
};

export const getSkillIcon = (skillName: string): React.ElementType => {
  return SKILL_ICONS[skillName] || FaExternalLinkAlt;
};
